### ISSUE TITLE
Using https://github.com/uutils/coreutils instead of BSDUtils

### ISSUE THREAD

**Issue by DestroyerXyz** [chimera-linux/community#2]
Hi,
I didn't know where to post this as the bsdutils repo did not have an issues section. I really like the project's software choices and bsdutils is definitely a step-up from GNU coreutils but I would like to recommend using https://github.com/uutils/coreutils instead as they are modern, GNU-free, fast and written in rust. Also, most importantly, meant to be at feature parity with GNU coreutils. 

Thanks

**Comment by q66** [comment]
I'm not going to do that

parity with gnu coreutils is an anti-feature, written in rust is an anti-selling point

**Comment by DestroyerXyz** [comment]
I don't understand both of those reasons @q66

**Comment by q66** [comment]
fine, i'll write it down here so other people who might get an idea to open a similar issue don't do that

* I don't care about "gnu-free" per se. Feature parity with GNU coreutils is a non-goal. BSD tools are featureful enough already and coreutils contains tons of features that are pointless to harmful and I don't care for bringing them into the project.
* I could go on for hours why bringing rust into the core system is a terrible idea, but the gist of it boils down to this:
    1) Chimera aims to be bootstrappable, rust in bootstrap path necessarily means bringing in binary-only, self-hosting toolchains that require exactly 1 version older toolchain to compile themselves
    2) Chimera aims to be dynamically linked where possible, rust goes directly against that goal due to by-design unstable ABI
    3) Chimera aims to be portable, rust goes directly against that goal (in fact, uutils/coreutils right now works *only* on x86 and ARM, because of dependency on `ring` (through `rustls`) and its harmful maintainership)
    4) Chimera aims to be reasonably packageable and resilient to supply chain attacks and other web era nonsense, and rust, or specifically cargo, goes directly against that goal with its npm-tier dependency hell and crappy build scripts that not even rust team members can get right
    5) I want to make a system that I can enjoy working on. Mostly due to the above and other issues, I do not enjoy working with rust

therefore, no uutils/coreutils, and no rust in bootstrap path, and packaging of rust stuff in main/ will be limited to strictly vetted necessities (such as librsvg).
